name: Blog CI/CD
 
on: [push, repository_dispatch]
 
jobs:
  blog-cicd:
    name: Hexo blog build & deploy
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - name: Checkout codes
      uses: actions/checkout@v2
 
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
 
    - name: Install dependencies
      run: |
        npm install hexo-cli -g
        npm install yuque-hexo -g
        npm install
        yuque-hexo sync
    - name: Generate files
      run: hexo generate
       
    - name: Deploy blog
      run: |
        git config user.name "wikeys"
        git config user.email "wikeys@163.com"
        git add source/
        git commit -m "Auto Update at $(date +'%Y-%m-%d %H:%M:%S')"
        git push --force --quiet "htt
